[package]
name = "prog_btc_book"
version = "0.1.0"
authors = ["fhools <fhools@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
